### ISSUE TITLE
Question about Intention annotation

### ISSUE THREAD

**Issue by MoonBlvd** [aras62/PIE#10]
Hi Amir, while reading your code,  I found that the intention label generated in your dataset code is the same along a whole sequence, which could result in a problem that the a pedestrian's intention is still crossing even he/she just finished crossing, which seems to be wrong. Could you please explain it? Thank you!

**Comment by aras62** [comment]
Hi,
You are right about the changes in intention and it has to be updated throughout. In our work, we simplified the problem to increase the number of trajectories while predicting the intention of pedestrians on part of the data that was exactly the same as the data used in human experiments, i.e. up to the same critical points of prediction. Predicting beyond the critical points used in the experiments can be quite noisy because the intention model is not trained on such data. One way of handling this can be perhaps modifying the intention score based on the observation of the action, e.g. in this case if the crossing finished, we set the intention score very low (cannot be certain to set to 0), Another thing to consider is that when a pedestrian finishes crossing, s/he will very unlikely interact with the vehicle again, therefore s/he is not as important to the vehicle again.

**Comment by MoonBlvd** [comment]
Hi @aras62 Thank you so much for your response! You have mentioned modifying the intention score annotations based on the observation of the action. My understanding is that to modify the intention score annotations, we need to mannually look at each trajectory. Please let me know if there is a way to make it automatic.
