### ISSUE TITLE
annotation

### ISSUE THREAD

**Issue by salorsmile** [aras62/PIE#14]
hello Amir,

I'm new to pedstrain intent detection,I hope to get your help.
what's means the 'ab' in pedstrain ID annotation, eg:0_7_40b. In JAAD dataset.
And I need to transfer the ped_id datatype(str) to float, do you have any advise for the id unique.
I try to use str.replace('_','').replace('a','1')..and so on.  what do you think?
looking forward to your replay.

lee

**Comment by aras62** [comment]
Hi,

b in the JAAD Ids means that the pedestrian has associated behavioral tags, e.g. looking, walking,etc. The rest only have bounding box information. As converting the ids to integers, in order to make sure you are creating unique ids, use 3 digits for the video ids (set_video_pedestrian-id). if you don't care for set of video, just the numerical part of the id for each pedestrian should be unique. 

In the future, if you have any questions about the JAAD dataset, please refer to the corresponding git repository https://github.com/ykotseruba/JAAD

Amir
